---
title: "project"
author: "Tim"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE, warning = FALSE)
```

```{r}
#load necessary libraries
library(tidyverse) #readr, dplyr

#Visual
library(ggplot2)
library(corrplot)

#Analysis
library(leaps) #regsubsets
library(broom) #glance 
library(car) #

#load processed dataset
df <- read_csv("df.csv")
```

*EDA*
```{r,message=FALSE,warning=FALSE}
df %>% select("Lifetime") %>% 
  ggplot(aes(Lifetime))+geom_histogram()
```


```{r}
#Feature Selection
#get the names of crucial features of Sequential, Forward and Backward Selection

#exclude two categorical variable, and year variable, which is predetermined to be included in the data. 
seqrep <- 
  regsubsets(Lifetime~., data = df %>% select(c(-1,-2,-3)), 
                     nvmax = 3, method = "seqrep") %>% 
  summary()
seqrep<- as.data.frame(seqrep$which)
seqrep<- seqrep[,apply(seqrep, 2, function(x) any(x ==T))] %>% 
  select(-1) %>% 
  colnames()

#forward selection
forward <- 
  regsubsets(Lifetime~., data = df %>% select(-1,-2,-3), 
                      nvmax = 3, method = "forward") %>% 
  summary()
forward<- as.data.frame(forward$which)
forward<- forward[,apply(forward, 2, function(x) any(x ==T))] %>% 
  select(-1) %>% 
  colnames()


#backward selection
backward <- 
  regsubsets(Lifetime~., data = df %>% select(-1,-2,-3), 
                      nvmax = 3, method = "backward") %>% 
  summary()
backward<- as.data.frame(backward$which)
backward<- backward[,apply(backward, 2, function(x) any(x ==T))] %>% 
  select(-1) %>% 
  colnames()


feature_select_result <- cbind(seqrep,forward,backward)
feature_select_result
```



```{r}

#Compare AIC BIC Adjusted R^2 etc, then we decide to use Forward Selection result
mod_for <- lm (as.formula(paste("Lifetime ~ ", paste(forward, collapse= "+"))),df) %>% 
  glance() %>% 
  select(1,2,6,9,10)
mod_back <- lm (as.formula(paste("Lifetime ~ ", paste(backward, collapse= "+"))),df) %>% 
  glance() %>% 
  select(1,2,6,9,10)
cbind(Type=c("Forward Selection", "Backward Selection"),
      rbind(mod_for,mod_back))
```

```{r}
#update our dataframe of interest
#The reason to include Country and year into df is for explaining the outcome through historical events(War, Disease etc.). 
forward <- str_replace_all(forward,"`","")
df <- 
  df %>% 
  select(Country, Continent, Year, forward, Lifetime) %>% 
  rename(HIV = `Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)`) 

#Use Symbox Function to see transformation needed for the variables

par(mfrow=c(2,2))
symbox(df$Year)
symbox(df$Household)
symbox(df$Education)
symbox(df$HIV)
```


```{r}

df

write.csv(df,"lifeexpectancy.csv", row.names = T)

```


```{r}
#Use the implied method by Symbox Function to transform the variables
df <- 
  df %>% 
  mutate(Household=log(Household),
         Education = Education^0.5,
         HIV = log(HIV+1)) #add 1 to avoid the log 0 situation
```


```{r}
#Correlation Plot
df %>% 
  select(Year,Household,Education,HIV,Lifetime) %>% 
  cor() %>% 
  corrplot(tl.col="black")

```

```{r}
#Full Model
mod <- lm(Lifetime ~ Year+ Household + Education + HIV + Continent,df) 
mod %>% 
  summary()
```

```{r}
#Usinf CV to test for overfitting

set.seed(827)

#Train test split; using 80% as training
sample <- sample(c(TRUE, FALSE), nrow(df), replace=TRUE, prob=c(0.8,0.2))
train  <- df[sample, ]
test   <- df[!sample, ]

# Cross-Validation
set.seed(123)
train.control <- trainControl(method = "cv", 
                              number = 10, repeats = 3)
# Train the model
model <- train(Lifetime ~., data = train %>% select(-1), method = "glm",
               trControl = train.control)
pred <- predict(model,test)

# Summarize the results
model$resample
```


```{r}
#Variance Assumption Check
plot(mod)
```



